# Generated by Django 5.2.5 on 2025-08-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=12)),
                ('close', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='makeportfol_date_4a852c_idx'), models.Index(fields=['ticker'], name='makeportfol_ticker_1d6c90_idx')],
                'unique_together': {('date', 'ticker')},
            },
        ),
    ]
